---
title: "Lab-05 Homework "
output: html_document
---

## Questions

### 1. You have rolled an unbiased die 10000 times. How many times did you see identical numbers in two consecutive rolls of a die? (Hint: use for loops) (5pts)
```{r}
rolls <- sample(1:6, size = 10000, replace = TRUE)

# Method 1
counter <- 0
for(dummy in 2:length(rolls)){
  if(rolls[dummy - 1] == rolls[dummy]){
    counter <- counter + 1
  }
}

counter2 <- 0
for(dummy in 1:(length(rolls)-1)){
  if(rolls[dummy] == rolls[dummy + 1]){
    counter2 <- counter2 + 1
  }
}

counter
counter2


# Method 2
last_roll <- 0
counter3 <- 0

for(dummy in rolls){
  if(dummy == last_roll){
    counter3 <- counter3 + 1
  }
  last_roll <- dummy
}
counter3
```


### 2. Do you see a higher number when you use a biased die where even numbers are 3 times more likely than odd numbers? (2 pts)

```{r}
biased_rolls <- sample(1:6, size = 10000, replace = TRUE, prob = rep(c(1, 3), 3))
biased_rolls <- sample(1:6, size = 10000, replace = TRUE, prob = c(1, 3, 1, 3, 1, 3))

counter4 <- 0
for(dummy in 2:length(biased_rolls)){
  if(biased_rolls[dummy - 1] == biased_rolls[dummy]){
    counter4 <- counter4 + 1
  }
}

counter4
```


### 3. Answer questions 1 and 2 without using for loops. (3 pts)
```{r}
# rolls
# biased_rolls

# Method 1
vector_a <- rolls[1:(length(rolls)-1)]
vector_b <- rolls[2:length(rolls)]

comp_vec <- ifelse(vector_a == vector_b, 1, 0)
sum(comp_vec)

sum(vector_a == vector_b)

# Method 2
diff_vec <- diff(rolls)
table(diff_vec)["0"]
```
















